import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {cn} from "@/styles/cn"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sik-Layout',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({children}:RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(`
        min-h-screen antialiased bg-zinc-50`,
        inter.className
      )}
      >{children}</body>
    </html>
  )
}
